# Generated by Django 4.0.5 on 2022-06-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maxsulot',
            old_name='ompor',
            new_name='ombor',
        ),
    ]
